pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver Job, Skipped because it was failing to get the jar file!'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job complete!'
            }
        }
    }
}
